import { marked } from '../node_modules/marked/lib/marked.esm.js';

const $ = (id) => document.getElementById(id);
const paths = {
  spark:'M12 2c1 5.5 4.5 9 10 10-5.5 1-9 4.5-10 10C11 16.5 7.5 13 2 12 7.5 11 11 7.5 12 2Z M5 3l.5 2L8 6l-2.5.5L5 9l-.5-2.5L2 6l2.5-1Z',
  chat:'M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-2 2v-9.5A8.5 8.5 0 0 1 10.5 4h2A8.5 8.5 0 0 1 21 11.5Z',
  code:'m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18',
  plus:'M12 5v14M5 12h14',search:'m21 21-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z',folder:'M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z',panel:'M8 3v18M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z',chevron:'m8 10 4 4 4-4',arrowUp:'M12 19V5m-6 6 6-6 6 6',arrowRight:'M5 12h14m-6-6 6 6-6 6',minus:'M5 12h14',square:'M5 5h14v14H5Z',x:'m6 6 12 12M6 18 18 6',play:'m7 4 14 8-14 8V4Z',
  brain:'M12 5a3 3 0 0 0-6-1 4 4 0 0 0-3 6 4 4 0 0 0 0 6 4 4 0 0 0 3 4 3 3 0 0 0 6-1V5Zm0 0a3 3 0 0 1 6-1 4 4 0 0 1 3 6 4 4 0 0 1 0 6 4 4 0 0 1-3 4 3 3 0 0 1-6-1M6 4v3m0 10v3m12-16v3m0 10v3',
  bulb:'M9 18h6m-5 3h4M8 14a6 6 0 1 1 8 0c-1.5 1-1 2-1 2H9s.5-1-1-2Z',pen:'m15 4 5 5M4 20l5-1L21 7a2 2 0 0 0 0-3l-1-1a2 2 0 0 0-3 0L5 15l-1 5Z',files:'M8 3h9l4 4v12H8V3Zm9 0v5h4M4 7H2v15h14v-2',terminal:'M8 8l4 4-4 4m6 0h3M3 3h18v18H3Z',shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4Zm-4 10 3 3 5-6',sliders:'M4 7h4m4 0h8M4 17h8m4 0h4M8 4v6m4-6v6M12 14v6m4-6v6',sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0Z',settings:'m10 2-1 3-3 1-3-1-1 4 2 2v3l-2 2 2 4 3-1 3 1 1 2h4l1-3 3-1 2-2-1-3V9l1-2-3-3-3 1-1-3h-4ZM16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z'
};
function icon(name){return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.chat}"/></svg>`;}
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
const desktop=window.desktop;
let settings={model:'deepseek-flash',thinking:false,baseUrl:'https://api.deepseek.com',theme:'system',hasApiKey:false,workspace:null};
let sessions=[],currentId=null,mode='chat',attachment=null,engineState='stopped',pendingDelete=null,toastTimer,saveTimer,modelSaving=false;
const requests=new Map();
const escapeHTML=(s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cleanError=e=>(e.message||String(e)).replace(/^Error invoking remote method '[^']+': Error: /,'');
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),4500);}
function current(){return sessions.find(s=>s.id===currentId);}
function currentRequest(){return [...requests].find(([,r])=>r.sessionId===currentId);}
async function persist(){try{if(desktop)await desktop.saveHistory(sessions);else localStorage.setItem('deepseek-studio-preview',JSON.stringify(sessions));}catch(e){toast(cleanError(e));}}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(persist,300);}
function applyTheme(){const dark=settings.theme==='dark'||(settings.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.dataset.theme=dark?'dark':'light';}
matchMedia('(prefers-color-scheme: dark)').addEventListener('change',applyTheme);
function updateModelSelector(){
  const select=$('model-select');
  select.querySelector('[data-custom-model]')?.remove();
  if(![...select.options].some(option=>option.value===settings.model)){
    const option=new Option(settings.model,settings.model);
    option.dataset.customModel='true';
    select.add(option);
  }
  select.value=settings.model;
  select.disabled=modelSaving;
}
$('model-select').addEventListener('change',async event=>{
  const model=event.target.value;
  const previous=settings.model;
  if(modelSaving||model===previous)return;
  settings.model=model;
  modelSaving=true;
  updateModelSelector();
  try{
    if(desktop)await desktop.saveSettings({model});
  }catch(error){
    settings.model=previous;
    toast('模型选择未保存：'+cleanError(error));
  }finally{
    modelSaving=false;
    updateModelSelector();
  }
});
function updateSettingsUI(){applyTheme();updateModelSelector();$('think-button').setAttribute('aria-pressed',String(settings.thinking));$('project-label').textContent=settings.workspace?settings.workspace.split(/[\\/]/).filter(Boolean).pop():'打开本地项目';$('project-label').title=settings.workspace||'';$('code-workspace').innerHTML=settings.workspace?`${escapeHTML(settings.workspace.split(/[\\/]/).filter(Boolean).pop())}<small>${escapeHTML(settings.workspace)}</small>`:'选择一个项目文件夹<small>代码和项目保留在你的电脑上</small>';}
function updateBounds(){if(!desktop)return;const rect=$('harness-host').getBoundingClientRect();desktop.setHarnessBounds({x:rect.x,y:rect.y,width:rect.width,height:rect.height}).catch(()=>{});desktop.setHarnessVisible(mode==='codex'&&engineState==='running'&&![...document.querySelectorAll('dialog')].some(x=>x.open)).catch(()=>{});}
new ResizeObserver(updateBounds).observe($('main')||document.querySelector('.main'));
new ResizeObserver(updateBounds).observe($('harness-host'));
async function setMode(next){mode=next;$('chat-mode').setAttribute('aria-selected',String(next==='chat'));$('code-mode').setAttribute('aria-selected',String(next==='codex'));$('chat-view').classList.toggle('hidden',next!=='chat');$('code-view').classList.toggle('hidden',next!=='codex');$('header-title').textContent='DeepSeek';$('header-subtitle').textContent=next==='chat'?'Chat':'Harness';$('new-label').textContent=next==='chat'?'新建对话':'Chat 新对话';if(desktop)await desktop.setMode(next);updateBounds();}
function renderHistory(){const list=[...sessions].sort((a,b)=>b.updatedAt-a.updatedAt);$('history-count').textContent=list.length||'';$('history-list').innerHTML=list.length?list.map(s=>`<div class="history-row ${s.id===currentId?'active':''}"><button data-session="${escapeHTML(s.id)}" title="${escapeHTML(s.title)}">${escapeHTML(s.title)}</button><button class="delete" data-delete="${escapeHTML(s.id)}" title="删除对话" aria-label="删除 ${escapeHTML(s.title)}">×</button></div>`).join(''):'<div class="history-empty">你的对话会出现在这里。<br>从一个新问题开始吧。</div>';}
function markdown(content){return DOMPurify.sanitize(marked.parse(content||'',{breaks:true,gfm:true}),{FORBID_TAGS:['img','style','input','form','iframe'],FORBID_ATTR:['style']});}
function renderMessages(scroll=false){const session=current();const messages=session?.messages||[];const empty=messages.length===0;$('welcome').classList.toggle('hidden',!empty);$('suggestions').classList.toggle('hidden',!empty);$('chat-view').classList.toggle('is-empty',empty);$('messages').innerHTML=messages.map((m,index)=>m.role==='user'?`<article class="message user"><div class="user-bubble">${escapeHTML(m.displayContent||m.content)}</div></article>`:`<article class="message assistant"><div class="message-heading">${icon('spark')}DeepSeek</div><div class="message-body">${m.reasoning?`<details class="reasoning"><summary>思考过程</summary><pre>${escapeHTML(m.reasoning)}</pre></details>`:''}${m.content?markdown(m.content):(m.pending?'<div class="message-pending">正在思考…</div>':'')}${m.error?`<div class="message-error">${escapeHTML(m.error)}</div>`:''}${m.cancelled?'<div class="field-help">回复已停止</div>':''}</div>${m.content?`<div class="message-tools"><button data-copy="${index}">复制回复</button></div>`:''}</article>`).join('');const req=currentRequest();$('send-button').innerHTML=icon(req?'square':'arrowUp');$('send-button').classList.toggle('streaming',Boolean(req));$('send-button').setAttribute('aria-label',req?'停止生成':'发送消息');if(scroll)$('conversation-scroll').scrollTop=$('conversation-scroll').scrollHeight;}
function newChat(){currentId=null;attachment=null;$('prompt').value='';renderAttachment();renderHistory();renderMessages();setMode('chat');$('prompt').focus();}
function selectSession(id){currentId=id;attachment=null;$('prompt').value='';renderAttachment();renderHistory();renderMessages(true);setMode('chat');}
async function sendMessage(){const running=currentRequest();if(running){await desktop?.cancelChat(running[0]);return;}const prompt=$('prompt').value.trim();if(!prompt)return;if(!desktop){toast('请在桌面应用中配置 API Key 后发送消息。');openSettings();return;}if(!settings.hasApiKey){openSettings();$('settings-error').textContent='请先添加 API Key，保存后再发送。';return;}let session=current();if(!session){if(sessions.length>=500){toast('最多保存 500 个对话，请先导出并删除部分旧对话。');return;}session={id:crypto.randomUUID(),title:prompt.slice(0,28),createdAt:Date.now(),updatedAt:Date.now(),messages:[]};sessions.unshift(session);currentId=session.id;}const fullContent=attachment?`${prompt}\n\n附件 ${attachment.name}：\n\n${attachment.text}`:prompt;session.messages.push({role:'user',content:fullContent,displayContent:attachment?`${prompt}\n📎 ${attachment.name}`:prompt});const apiMessages=session.messages.filter(m=>m.content&&!m.error).map(m=>({role:m.role,content:m.content}));const assistant={role:'assistant',content:'',reasoning:'',pending:true};session.messages.push(assistant);const requestId=crypto.randomUUID();requests.set(requestId,{sessionId:session.id,assistant});session.updatedAt=Date.now();$('prompt').value='';$('prompt').style.height='';attachment=null;renderAttachment();renderHistory();renderMessages(true);queueSave();try{await desktop.chat({requestId,messages:apiMessages,model:settings.model,thinking:settings.thinking});}catch(e){assistant.pending=false;assistant.error=cleanError(e);requests.delete(requestId);renderMessages(true);queueSave();}}
let streamRender=false;
desktop?.onChatEvent(event=>{const req=requests.get(event.requestId);if(!req)return;const message=req.assistant;if(event.type==='delta')message.content+=event.text||'';if(event.type==='reasoning')message.reasoning+=event.text||'';if(event.type==='done'||event.type==='error'){message.pending=false;message.cancelled=event.cancelled||false;if(event.type==='error')message.error=event.text;requests.delete(event.requestId);queueSave();}if(req.sessionId===currentId&&!streamRender){streamRender=true;requestAnimationFrame(()=>{streamRender=false;const el=$('conversation-scroll');const nearBottom=el.scrollHeight-el.scrollTop-el.clientHeight<120;renderMessages(nearBottom);});}});
function engineStatus(status){engineState=status.state;const names={stopped:'Harness 待启动',starting:'Harness 启动中',running:'Harness 已连接',stopping:'Harness 正在停止',error:'Harness 连接异常'};const label=names[status.state]||'Harness 待启动';$('engine-mini-label').textContent=label;$('settings-engine-label').textContent=label;$('engine-bar-label').textContent=status.workspace?`Harness · ${status.workspace.split(/[\\/]/).pop()}`:label;['engine-dot','settings-engine-dot'].forEach(id=>{$(id).className=`status-dot ${status.state==='running'?'active':status.state==='starting'?'starting':status.state==='error'?'error':''}`;});$('code-landing').classList.toggle('hidden',status.state==='running');$('harness-host').classList.toggle('hidden',status.state!=='running');$('engine-bar').classList.toggle('hidden',status.state!=='running');$('start-engine').disabled=['starting','stopping'].includes(status.state);$('start-engine').innerHTML=icon('play')+(status.state==='starting'?'正在启动，首次可能需要几分钟…':status.state==='error'?'重新打开工作区':'打开编程工作区');$('engine-explanation').textContent=status.state==='error'?status.message:status.state==='starting'?'正在加载官方 Harness 插件与本地运行环境，请稍候。':'首次进入后，在 Harness 设置中配置模型，即可开始任务。';updateBounds();}
desktop?.onHarnessStatus(engineStatus);
async function workspace(){if(!desktop){toast('选择本地项目需要使用桌面应用。');return;}const selected=await desktop.chooseWorkspace();if(selected){settings.workspace=selected;updateSettingsUI();setMode('codex');if(engineState==='running')toast('已选择新项目；停止当前引擎后重新打开即可切换。');}}
async function connect(){if(!desktop){toast('请启动桌面应用后打开 Harness 工作区。');return;}if(!settings.workspace){await workspace();if(!settings.workspace)return;}await desktop.connectHarness();}
async function showDialog(id){if(desktop)await desktop.setHarnessVisible(false);$(id).showModal();}
function openSettings(){$('api-key').value='';$('api-key').placeholder=settings.hasApiKey?'已保存 · 留空保持现有密钥':'sk-…';$('base-url').value=settings.baseUrl;$('theme-select').value=settings.theme;$('settings-error').textContent='';$('key-state').textContent=settings.hasApiKey?'密钥已加密保存，填写新密钥可替换。':'密钥加密保存在当前电脑，不会显示在历史记录中。';showDialog('settings-dialog');}
document.querySelectorAll('dialog').forEach(dialog=>{dialog.addEventListener('close',()=>{if(dialog.id==='settings-dialog')$('api-key').value='';updateBounds();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});});
$('settings-form').addEventListener('submit',async e=>{e.preventDefault();const next={baseUrl:$('base-url').value.trim(),theme:$('theme-select').value};const key=$('api-key').value.trim();if(key)next.apiKey=key;try{if(desktop){const saved=await desktop.saveSettings(next);settings={...settings,baseUrl:saved.baseUrl,theme:saved.theme,hasApiKey:saved.hasApiKey};}else{delete next.apiKey;settings={...settings,...next};}updateSettingsUI();$('settings-dialog').close();toast(desktop?'设置已保存':'预览外观已更新；API 设置请在桌面应用中保存。');}catch(error){$('settings-error').textContent=cleanError(error);}});
function renderSearch(){const query=$('search-input').value.toLowerCase();const found=sessions.filter(s=>`${s.title} ${s.messages.map(m=>m.content).join(' ')}`.toLowerCase().includes(query));$('search-results').innerHTML=found.length?found.map(s=>`<button data-session="${escapeHTML(s.id)}">${escapeHTML(s.title)}<small>${escapeHTML(s.messages.find(m=>m.role==='user')?.displayContent||s.messages.find(m=>m.role==='user')?.content||'')}</small></button>`).join(''):'<div class="search-empty">'+(query?'没有找到相关对话':'还没有对话，试着发起第一个问题吧')+'</div>';}
$('search-input').addEventListener('input',renderSearch);
function renderAttachment(){$('attachment-chip').classList.toggle('hidden',!attachment);$('attachment-chip').innerHTML=attachment?`<span>📎 ${escapeHTML(attachment.name)} · ${(attachment.size/1024).toFixed(1)} KB</span><button data-action="remove-attachment" aria-label="移除附件">×</button>`:'';}
$('file-input').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>128*1024){toast('请添加 128 KB 以内的文本或代码文件。');e.target.value='';return;}const text=await file.text();if(text.includes('\u0000')){toast('暂时仅支持文本和代码文件。');return;}attachment={name:file.name,text,size:file.size};renderAttachment();e.target.value='';});
async function exportHistory(){const content=sessions.map(s=>`# ${s.title}\n\n${s.messages.map(m=>`## ${m.role==='user'?'你':'DeepSeek'}\n\n${m.content}${m.reasoning?'\n\n<details><summary>思考过程</summary>\n\n'+m.reasoning+'\n\n</details>':''}`).join('\n\n')}`).join('\n\n---\n\n');if(desktop){const result=await desktop.exportHistory({content:content||'# DeepSeek\n\n暂无对话。',filename:'DeepSeek-对话-'+new Date().toISOString().slice(0,10)+'.md'});if(result.saved)toast('对话已导出。');return;}const blob=new Blob([content||'# DeepSeek\n\n暂无对话。'],{type:'text/markdown;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`DeepSeek-对话-${new Date().toISOString().slice(0,10)}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
const actions={chat:()=>setMode('chat'),codex:()=>setMode('codex'),new:newChat,sidebar:()=>{$('app').classList.toggle('sidebar-collapsed');updateBounds();},settings:openSettings,search:()=>{$('search-input').value='';renderSearch();showDialog('search-dialog');},workspace,connect,disconnect:()=>desktop?.disconnectHarness(),send:sendMessage,attach:()=>$('file-input').click(),'remove-attachment':()=>{attachment=null;renderAttachment();},think:async()=>{settings.thinking=!settings.thinking;updateSettingsUI();if(desktop)await desktop.saveSettings({thinking:settings.thinking});},theme:async()=>{settings.theme=document.body.dataset.theme==='dark'?'light':'dark';applyTheme();if(desktop)await desktop.saveSettings({theme:settings.theme});},export:exportHistory,'delete-key':async()=>{if(desktop){const saved=await desktop.saveSettings({apiKey:''});settings.hasApiKey=saved.hasApiKey;openSettingsFieldsOnly();toast('API Key 已移除。');}else toast('预览中没有保存密钥。');}};
function openSettingsFieldsOnly(){$('api-key').value='';$('api-key').placeholder='sk-…';$('key-state').textContent='尚未配置 API Key。';}
document.addEventListener('click',async e=>{const el=e.target.closest('button,a');if(!el)return;try{if(el.dataset.close){$(el.dataset.close).close();return;}if(el.dataset.action){await actions[el.dataset.action]?.();return;}if(el.dataset.window){if(desktop)await desktop.windowControl(el.dataset.window);return;}if(el.dataset.prompt){$('prompt').value=el.dataset.prompt;$('prompt').focus();return;}if(el.dataset.session){if($('search-dialog').open)$('search-dialog').close();selectSession(el.dataset.session);return;}if(el.dataset.delete){pendingDelete=el.dataset.delete;showDialog('confirm-dialog');return;}if(el.dataset.copy){await navigator.clipboard.writeText(current().messages[Number(el.dataset.copy)].content);toast('回复已复制。');return;}if(el.tagName==='A'){if(el.hasAttribute('download'))return;e.preventDefault();if(desktop)await desktop.openExternal(el.href);else toast('项目地址：https://github.com/deepseek-ai/deepseek-harness');}}catch(error){toast(cleanError(error));}});
$('confirm-delete').addEventListener('click',async()=>{for(const [id,r]of requests)if(r.sessionId===pendingDelete){await desktop?.cancelChat(id);requests.delete(id);}sessions=sessions.filter(s=>s.id!==pendingDelete);if(currentId===pendingDelete)currentId=null;$('confirm-dialog').close();renderHistory();renderMessages();queueSave();});
$('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();sendMessage().catch(error=>toast(cleanError(error)));}});
$('prompt').addEventListener('input',()=>{$('prompt').style.height='auto';$('prompt').style.height=Math.min($('prompt').scrollHeight,180)+'px';});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!document.querySelector('dialog[open]'))actions.search();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'){e.preventDefault();if(!document.querySelector('dialog[open]'))newChat();}});
window.addEventListener('beforeunload',()=>{if(!desktop){clearTimeout(saveTimer);persist();}});
async function initialize(){try{if(desktop){[settings,sessions]=await Promise.all([desktop.getSettings(),desktop.getHistory()]);}else sessions=JSON.parse(localStorage.getItem('deepseek-studio-preview')||'[]');if(!Array.isArray(sessions))sessions=[];sessions=sessions.filter(s=>s&&typeof s.id==='string'&&Array.isArray(s.messages));for(const s of sessions)for(const m of s.messages)if(m.pending){m.pending=false;m.cancelled=true;}}catch(error){toast(cleanError(error));}updateSettingsUI();renderHistory();renderMessages();updateBounds();}
initialize();

desktop?.onBeforeClose(async()=>{clearTimeout(saveTimer);await persist();await desktop.finishClose();});
